### ISSUE TITLE
Add support to image labels

### ISSUE THREAD

**Issue by ltagliamonte-dd** [kubernetes/cri-api#10]
Currently the Type Image doesn't provide label information associated with the image at creation time, for example in a Dockerfile it is possible to add labels by using:
```
LABEL "com.mydomain.image.distro.id"="${DISTRO_ID}" \
      "com.mydomain.image.distro.codename"="${DISTRO_CODENAME}" \
      "com.mydomain.image.distro.release"="${DISTRO_RELEASE}" \
      "com.mydomain.image.distro.build_id"="${BUILD_ID}"
```
Would be possible to improve this in future?
I'm working on an image stats collector, for internal reports, and I was looking to retrieve this info in a general way instead of having two clients, one for docker and another for containerd.

**Comment by SergeyKanzhelev** [comment]
can you please file this request at https://github.com/kubernetes/kubernetes/? This repository is read only.

/close
