### ISSUE TITLE
Uploading the CRI Socket information ends up with error uploading crisocket!

### ISSUE THREAD

**Issue by PontusTideman** [kubernetes/cri-api#5]
So, first things first!

For the last couple of weeks we have tried to pin point what is going on and what is not working. Everytime we ends up with both `patchnode.go:30] [patchnode] Uploading the CRI Socket information "/var/run/dockershim.sock" to the Node API object "DELTED_INFO" as an annotation
[kubelet-check] Initial timeout of 40s passed.
timed out waiting for the condition
error uploading crisocket`

The setup is running on Debain 10, with Docker and Kubernetes + Flannel as the CNI. All ports that is necessary for it to work is open, and we even allowed all traffic between the cluster, but everytime we ends up with the crisocket time out as above.

Today I did a reset on master + slaves, replaced the Flannel CNI with Calico and all went well!

The only thing I did was to replace the Flannel with Calico, everything else is untouched. So it looks like there is a problem with the CRI plugin and the Flannel CNI, but I can't put a finger on it what is not working.

**Comment by SergeyKanzhelev** [comment]
@PontusTideman you may have more luck filing this issue in kubernetes repository. This repository is [managed by bot](https://github.com/kubernetes/cri-api/blob/master/CONTRIBUTING.md#user-content-contributing-guidelines:~:text=This%20repository%20is%20published%20from%20kubernetes%2Fkubernetes%2Fstaging%2Fsrc%2Fk8s.io%2Fcri%2Dapi,by%20the%20kubernetes%20publishing%2Dbot.) as a copy of a folder in kubernetes repository.
