### ISSUE TITLE
How to get the specific container ContainerConfig by cri-api ?

### ISSUE THREAD

**Issue by Colstuwjx** [kubernetes/cri-api#9]
Hi team,

I'm working on some tools which need to be interacting with cri-api, but  I found that it's hard to get the ContainerConfig of a running container:

```go
criapi, err := remote.NewRemoteRuntimeService("/run/containerd/containerd.sock", containerd.WithTimeout(10 * time.Second))
if err != nil {
     panic(err)
}
cid = "<A_CONTAINER_ID>"
containerStatus, err := criapi.ContainerStatus(cid)
if err != nil {
     panic(err)
}
// But there is no container config data, e.g. container envs.
```

So we did have a [ContainerConfig](https://github.com/kubernetes/cri-api/blob/aa6a44c/pkg/apis/runtime/v1/api.pb.go#L4303) while doing `CreateContainer`, how do we get such config data for running containers?

Thanks!

**Comment by SergeyKanzhelev** [comment]
Can you please post this on https://github.com/kubernetes/kubernetes/? This repository is read only.

/close
